import Nav from '@/components/auth/Nav';
import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Postit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} mx-auto max-w-screen-xl  h-screen px-5 cursor-default`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
